// Realistic dummy data for the waste marketplace

export const wasteCategories = [
  'Metal Scrap', 'Plastic Waste', 'Chemical Byproducts', 'Textile Waste',
  'Wood & Paper', 'Glass', 'Electronic Waste', 'Organic Waste',
  'Construction Debris', 'Rubber & Tires',
]

export const hazardLevels = ['Non-hazardous', 'Low', 'Moderate', 'High']

export const listings = [
  {
    id: '1',
    title: 'Steel Mill Slag — Grade A',
    category: 'Metal Scrap',
    company: 'Northgate Steelworks Ltd.',
    location: 'Jamshedpur, Jharkhand',
    quantity: '450 tonnes',
    price: '₹8,200/tonne',
    hazard: 'Non-hazardous',
    condition: 'Unprocessed',
    description: 'High-calcium steel slag from blast furnace operations. Ideal for cement manufacturing, road construction aggregate, or soil conditioning. Consistent chemical composition with monthly test reports available. Regular supply of 200+ tonnes/month guaranteed.',
    aiClassification: 'Calcium Silicate Slag (CAS: 65997-17-3)',
    aiValuation: '₹7,800 – ₹9,100/tonne',
    aiConfidence: 92,
    co2Saved: '1,240 kg CO₂e per tonne reused',
    postedAt: '2 days ago',
    bids: 7,
    image: null,
  },
  {
    id: '2',
    title: 'HDPE Drum Regrind — Clean, Single-Source',
    category: 'Plastic Waste',
    company: 'Meridian Petrochemicals',
    location: 'Vadodara, Gujarat',
    quantity: '12 tonnes',
    price: '₹42,000/tonne',
    hazard: 'Non-hazardous',
    condition: 'Ground / Shredded',
    description: 'Clean HDPE regrind from food-grade chemical drums. Single polymer source — no mixed plastics. Washed and granulated to 8-12mm flake. Melt flow index: 7.5 g/10min. Perfect for pipe extrusion or blow molding.',
    aiClassification: 'High-Density Polyethylene (HDPE, Resin Code 2)',
    aiValuation: '₹38,000 – ₹45,000/tonne',
    aiConfidence: 97,
    co2Saved: '3,100 kg CO₂e per tonne recycled',
    postedAt: '5 hours ago',
    bids: 3,
    image: null,
  },
  {
    id: '3',
    title: 'Spent Caustic Soda — Recoverable NaOH',
    category: 'Chemical Byproducts',
    company: 'Zenith Refining & Energy',
    location: 'Mathura, Uttar Pradesh',
    quantity: '80 KL',
    price: '₹6,500/KL',
    hazard: 'Moderate',
    condition: 'Liquid — tanker pickup',
    description: 'Spent caustic from crude desulfurization. NaOH concentration 8-12%. Contains mercaptides and sulfides. Suitable for caustic recovery units or wastewater neutralization. MSDS and transport documentation provided.',
    aiClassification: 'Spent Caustic — Sulfidic (EPA K062 equivalent)',
    aiValuation: '₹5,200 – ₹7,800/KL',
    aiConfidence: 85,
    co2Saved: '890 kg CO₂e per KL recovered',
    postedAt: '1 day ago',
    bids: 2,
    image: null,
  },
  {
    id: '4',
    title: 'Cotton Selvedge & Cutting Waste',
    category: 'Textile Waste',
    company: 'Solaria Industrial Textiles',
    location: 'Ahmedabad, Gujarat',
    quantity: '6 tonnes/month',
    price: '₹15,000/tonne',
    hazard: 'Non-hazardous',
    condition: 'Baled',
    description: 'Clean cotton selvedge waste from denim weaving. 100% cotton, undyed edges and cutting room scraps. Baled in 200kg blocks. Consistent quality — same mill, same raw material. Ideal for recycled yarn spinning or industrial wiping cloth.',
    aiClassification: 'Post-industrial Cotton Fiber Waste',
    aiValuation: '₹12,000 – ₹18,000/tonne',
    aiConfidence: 94,
    co2Saved: '5,200 kg CO₂e per tonne reused',
    postedAt: '3 days ago',
    bids: 11,
    image: null,
  },
  {
    id: '5',
    title: 'Fly Ash — Class F, Dry',
    category: 'Construction Debris',
    company: 'ThermalGrid Energy Generation',
    location: 'Dadri, Uttar Pradesh',
    quantity: '2,000 tonnes',
    price: '₹800/tonne',
    hazard: 'Low',
    condition: 'Dry — silo storage',
    description: 'Class F fly ash from coal-fired thermal power generation. Low calcium (<5%), high silica. Meets IS 3812 Part 1 standards. Available for bulk pickup or rail transport. Excellent pozzolanic properties for concrete and brick manufacturing.',
    aiClassification: 'Coal Combustion Residual — Class F Fly Ash',
    aiValuation: '₹600 – ₹1,100/tonne',
    aiConfidence: 98,
    co2Saved: '420 kg CO₂e per tonne used in concrete',
    postedAt: '6 hours ago',
    bids: 15,
    image: null,
  },
  {
    id: '6',
    title: 'E-Waste PCB Boards — Mixed Grade',
    category: 'Electronic Waste',
    company: 'CyberCore Infrastructure Systems',
    location: 'Bangalore, Karnataka',
    quantity: '800 kg',
    price: '₹280/kg',
    hazard: 'Moderate',
    condition: 'Decommissioned — untreated',
    description: 'Mixed PCB boards from end-of-life server and desktop equipment. Contains recoverable copper, gold, palladium, and tin. R2-certified chain of custody documentation available. Quarterly batches of 500-1000 kg.',
    aiClassification: 'Waste PCBs (Basel Convention A1180)',
    aiValuation: '₹240 – ₹320/kg',
    aiConfidence: 88,
    co2Saved: '14,000 kg CO₂e per tonne vs virgin mining',
    postedAt: '4 days ago',
    bids: 9,
    image: null,
  },
]

export const sellerStats = {
  activeListings: 8,
  totalBids: 47,
  co2Saved: '12.4 tonnes',
  revenue: '₹18,40,000',
  conversionRate: '34%',
}

export const recentActivity = [
  { action: 'New bid received', detail: 'Steel Mill Slag — ₹8,400/tonne from Apex Matrix Materials', time: '2 hours ago' },
  { action: 'Listing approved', detail: 'HDPE Drum Regrind now live on marketplace', time: '5 hours ago' },
  { action: 'Deal closed', detail: 'Fly Ash — 500 tonnes sold to Apex Matrix Materials', time: '1 day ago' },
  { action: 'New bid received', detail: 'Cotton Selvedge — ₹16,200/tonne from Aura Spinners', time: '1 day ago' },
  { action: 'Listing expired', detail: 'Rubber Crumb — relisted with updated pricing', time: '3 days ago' },
]
